### ISSUE TITLE
Missing cbor tag encoding

### ISSUE THREAD

**Issue by dignifiedquire** [ipld/js-ipld-dag-cbor#33]
The implementation of this that I did, used tag `258` for encoding links `{'/': mylink}` in cbor (ref: https://github.com/ipld/js-ipld-dag-cbor/blob/8f6c8491ac540b0fdf9d88d34f373d2f1e97c076/src/cbor.js#L13) which corresponds to the spec as far as I understand and it was planned to register this tag. 
What happened to this?

cc @diasdavid @whyrusleeping @jbenet

**Comment by dignifiedquire** [comment]
Original spec suggestion: https://github.com/ipfs/specs/pull/61

**Comment by diasdavid** [comment]
To my understanding of how things developed, once we figured out the `IPLD Format` interface and stopped talking about `CBOR` as the IPLD format and moved to have several IPLD formats, CBOR became just a schemaless serialisation format that maps 1:1 to JSON.

The local resolver has the job of figuring out which are links, and it could use CBOR tags for that, but is there any benefit? If CBOR was length prefixed (so that we could seek), then it could make sense as the deserialization of some values would be faster, but since it is not, I don't see the value.

On the `length prefixed for seeking` note, I'm very interested in having a `dag-ion` that uses [Amazon Ion](https://amznlabs.github.io/ion-docs/), it is a way simpler serialisation protocol (just look at the size of the spec) that does everything we need. Unfortunately there are no [Go or JavaScript implementations yet](https://github.com/amznlabs?utf8=%E2%9C%93&q=ion-&type=&language=).

**Comment by dignifiedquire** [comment]
> Go or JavaScript implementations yet.

I might accept the challenge, I like writing serialisers, especially fast ones ;)

**Comment by dignifiedquire** [comment]
A big benefit to using a specific tag would be performance, as we wouldn't have to scan all keys anymore when decoding. In either case we need to update the spec, as it still reflects the situation where it is expected to use a specific tag.

**Comment by diasdavid** [comment]
>  it still reflects the situation where it is expected to use a specific tag.

I believe we need to update the whole spec either way, it hasn't received any love AFAIK since August which was when CID came together and then September when IPLD Formats became a thing.

**Comment by ian-gtv** [comment]
FWIW, The Amazon ion implementation in Java looks much more complicated than the cbor implementation we are using.

**Comment by ianopolous** [comment]
FWIW, The Amazon ion implementation in Java looks much more complicated than the cbor implementation we are using.

**Comment by diasdavid** [comment]
@whyrusleeping your tags in go work as you replace the whole object or just the CID value:

```
// original
{
  someLink: {
    '/': '<someCID>'
  }
}
// a) representation of the version encoded with CID being converted
{
  someLink: {
    '/': CBORTAG
  }
}
// b) representation of the version encoded with the whole object
{
  someLink: CBORTAG
}
```

I believe it is option b), but I want to be sure.
