### ISSUE TITLE
sync interface

### ISSUE THREAD

**Issue by jbenet** [ipld/js-ipld-dag-cbor#7]
@mafintosh would like a sync interface here. @diasdavid why need async? (encoding/decoding should peg the cpu and not do io, right?)

**Comment by diasdavid** [comment]
sounds good :) the async unmarshelling happened cause of [`node-cbor`](https://www.npmjs.com/package/cbor). Found a [`cbor-sync`](https://www.npmjs.com/package/cbor-sync), we can move to that one :)

**Comment by jbenet** [comment]
make sure it has the same feature set? and that it really works? this helped me: https://github.com/jbenet/node-random-json-stream

**Comment by diasdavid** [comment]
Added the sync call :)

**Comment by dignifiedquire** [comment]
@diasdavid as far as I can tell the interface is sync currently. Can we close this then?

**Comment by mitar** [comment]
This looks async to me? https://github.com/ipld/js-ipld-dag-cbor/blob/master/src/util.js#L105

Is there a sync version of `cid` function?

**Comment by dignifiedquire** [comment]
It changed after my comment, and from what I know about the current implementation I don't think it will be possible to create a sync version without changing a lot of things for the worse

**Comment by mitar** [comment]
From what I am looking it, it is all sync, just fake async with `setImmediate`?

`serialize` is sync. `new CID` is sync. And we can use js-multihashing for multihashing, instead of js-multihashing-async.

I could try to make a pull request. What should be the API? Can I just break the API? Or should I make it so that if you do not pass callback, is sync? Or I add `*Sync` versions?

**Comment by dignifiedquire** [comment]
We don't want to use js-multihashing anymore because it increases the browser bundle by an unreasonable amount. If there is a need for a sync interface it could be its own module.

**Comment by mitar** [comment]
Hm, that is true:

```
$ curl -s https://unpkg.com/multihashing@0.3.1/dist/index.js | wc -c
  623081
$ curl -s https://unpkg.com/multihashing-async@0.4.3/dist/index.js | wc -c
  156535
```

Why is that? Shouldn't those two things be exactly the same, just API different?

**Comment by dignifiedquire** [comment]
@mitar that's because I rewrote it to use webcrypto where available, which means we don't have to send a bunch slow javascript to the browser. This is also the reason we are force to use async interfaces as webcrypto only exposes a promise based api. (Due to the reason that it's doing the actual work on a different OS thread)

**Comment by mitar** [comment]
Ohh. True. Webcrypto needs async. Then there is not really a way around this.

But serialize/deserialize could be then made sync, at least? And then `cid` could be async because of the multihash?

(BTW, I use [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl) on the server side to get the same WebCrypto API on the server side as well, so then code is really the same between client and server.)

**Comment by diasdavid** [comment]
@mitar as @dignifiedquire said, bundle size gets smaller and also by using native crypto libraries to the browser, we got a huge speed boost.

@mitar we also use node-webcrypto-ossl, it comes from https://github.com/libp2p/js-libp2p-crypto.

The order of events was:

- We moved multihashing to async, which made the operation of creating a new CID something that happens inside a callback
- That caused a breaking change that forced everyone that was using dag-pb, to calculate the multihash or CID in a step post deserialization, causing a lot of pain for users, after discusison, we reached the conclusion to make deserialization async for convinience and simplicity
  - https://github.com/ipld/js-ipld-dag-pb/blob/master/src/util.js#L31-L41
  - https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-node/create.js#L12-L58
- With deserialization being async, it made sense to make serialization async too, so that all the calls had a similar signature

**Comment by mitar** [comment]
Yea, seems reasonable. Not nice, but ... I am using [fibers](https://github.com/laverdet/node-fibers) anyway on the server side, so it worked out at the end for me.

**Comment by diasdavid** [comment]
I see. We are avoiding including (more) third party control flow libraries to our API calls and stick with what is stable/widely used. Async/Await is coming soon™ and we will be considering to make it available by the end of the year, until then (and unless there is a rampage of devs moving to async/await), we will keep using callbacks + promises.

Closing this issue for now.
