### ISSUE TITLE
Remove support for old-style links

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld-dag-cbor#84]
Currently there's still support for old style `{"/": "base-encoded-cid"}` style links. I think we should remove the support for this, so that consumers don't have "silent" breakage where a serialisation works as before, but de-serialisation doesn't.

**Comment by mikeal** [comment]
I'm +1 on doing this after `js-ipfs` has moved completely to the new API. 

Enforcing a symmetrical encode/decode seems like a good idea and the new IPLD specs have abandoned any "canonical" format.

**Comment by vmx** [comment]
Done with the release of version 0.14.

**Comment by alanshaw** [comment]
We implemented `dag put` on the CLI but because `ipld-dag-cbor` no longer supports this format for linking no links can be made:

```console
$ echo '{ "link": { "/": "bafyreidl34zuzoltv3ijlunrilncnzmczx53lfco4dzc6o77xy2f4dq7ce" } }' | ipfs dag put
```

Obviously we can't pass CID instances to IPLD from the CLI.

We're going to patch js-ipfs to convert these objects into CID instances until go-ipfs drops support for this.

Other ideas welcome!

**Comment by mikeal** [comment]
You should be able to just decode the JSON w/ the `dag-json` parser and then pass the decoded object on to whatever encoder they actually want. That link format is still the internal `dag-json` link format so it should work.

**Comment by alanshaw** [comment]
I think this is a good shout, but `dag-json` is not currently a dependency so I'm hesitant to add it.

**Comment by mikeal** [comment]
You could just wait until you take the new Block API, `dag-json` is in the default set of codecs and there’s better support for selectively including codecs when you want to trim the bundle.

In general, we should find creative ways to dynamically load the codecs we need instead of bundling them. If this feature is only needed by the CLI then we should pull that codec into the CLI utility and not into the entire default IPLD API.
